apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freeb.fullname" . }}
  labels:
    {{- include "freeb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "freeb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "freeb.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "freeb.serviceAccountName" . | default "default" }}
      {{- include "freeb.imagePullSecrets" . | nindent 6 }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "freeb.fullname" . }}
          image: {{ template "freeb.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ include "freeb.containers.port" . }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ include "freeb.containers.port" . }}
            {{- if .Values.livenessProbe.enabled }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ add1 .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            {{- else -}}
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ include "freeb.containers.port" . }}
            {{- if .Values.readinessProbe.enabled }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ add1 .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            {{- else -}}
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: HOST_HOSTNAME
            value: {{ include "freeb.fullname" . }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
